# Generated by Django 4.2.3 on 2023-08-15 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('type', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')])),
                ('file', models.FileField(blank=True, null=True, upload_to='user_files')),
                ('admin_approved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
