# Generated by Django 4.2.3 on 2023-08-15 07:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField(default=None)),
                ('course_image_url', models.URLField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date(2023, 8, 15))),
                ('type', models.CharField(choices=[('Math 1', 'Math 1'), ('Math 2', 'Math 2'), ('Math 3', 'Math 3'), ('Math 4', 'Math 4'), ('Math 5', 'Math 5'), ('Math 6', 'Math 6'), ('Math 7', 'Math 7'), ('Math 8', 'Math 8'), ('Math 9', 'Math 9'), ('Math 10', 'Math 10'), ('Math 11', 'Math 11'), ('Math 12', 'Math 12')])),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
