# Generated by Django 4.2.3 on 2023-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_createcourse_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcourse',
            name='course_image_url',
        ),
        migrations.AddField(
            model_name='createcourse',
            name='course_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
