# Generated by Django 4.2.3 on 2023-08-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_remove_createcourse_course_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcourse',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
